name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Audit dependencies
        uses: actions-rs/audit-check@v1
        with: { token: "${{ secrets.GITHUB_TOKEN }}" }
